version: "3"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    env_file:
      - ./.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/live/geo.avoin.org/fullchain.pem:/etc/letsencrypt/live/geo.avoin.org/fullchain.pem
      - /etc/letsencrypt/live/geo.avoin.org/privkey.pem:/etc/letsencrypt/live/geo.avoin.org/privkey.pem
      - ./certbot:/var/www/certbot
      - ${AVOIN_LOGS_PATH}:/var/log/nginx
      - ${AVOIN_DATA_PATH}:/data
    networks:
      - proxy-net
    restart: unless-stopped

networks:
  proxy-net:
    external: true
