version: "3"

services:
  nginx:
    image: nginx:1.23.1
    container_name: nginx
    env_file:
      - ./.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot:/var/www/certbot
      - ${AVOIN_LOGS_PATH}:/var/log/nginx
      - ./nginx/templates:/etc/nginx/templates
      - /etc/letsencrypt/live/gis.avoin.org/fullchain.pem:/etc/letsencrypt/live/gis.avoin.org/fullchain.pem
      - /etc/letsencrypt/live/gis.avoin.org/privkey.pem:/etc/letsencrypt/live/gis.avoin.org/privkey.pem
    networks:
      - proxy-net
    restart: unless-stopped

  postgis:
    build: ../docker-postgis
    container_name: postgis
    volumes:
      - /etc/letsencrypt/live/gis.avoin.org/fullchain.pem:/etc/letsencrypt/live/gis.avoin.org/fullchain.pem
      - /etc/letsencrypt/live/gis.avoin.org/privkey.pem:/etc/letsencrypt/live/gis.avoin.org/privkey.pem
      - /etc/letsencrypt/live/gis.avoin.org/server.crt:/etc/letsencrypt/live/gis.avoin.org/server.crt
      - /mnt/postgis-data:/var/lib/postgresql
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - FORCE_SSL=FALSE
      - SSL_DIR=/etc/letsencrypt/live/gis.avoin.org
      - SSL_CERT_FILE=/etc/letsencrypt/live/gis.avoin.org/fullchain.pem
      - SSL_KEY_FILE=/etc/letsencrypt/live/gis.avoin.org/privkey.pem
      - SSL_CA_FILE=/etc/letsencrypt/live/gis.avoin.org/server.crt
    restart: unless-stopped
    healthcheck:
      test: "exit 0"
    networks:
      - proxy-net
    shm_size: 4g

  geoserver:
    image: kartoza/geoserver:${GS_VERSION}
    container_name: geoserver
    depends_on:
      - postgis
    volumes:
      - ${AVOIN_DATA_PATH}:${GEOSERVER_DATA_DIR}
    ports:
      - ${GEOSERVER_PORT}:8080
    restart: unless-stopped
    environment:
      # - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
      # - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - TOMCAT_EXTRAS=${TOMCAT_EXTRAS}
      - INITIAL_MEMORY=${INITIAL_MEMORY}
      - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
     - proxy-net

networks:
  proxy-net:
    external: true
