version: "3"

services:

  geoserver:
    image: kartoza/geoserver:${GS_VERSION}
    container_name: geoserver
    # depends_on:
    #   - postgis
    volumes:
      - ${AVOIN_DATA_PATH}:${GEOSERVER_DATA_DIR}
    ports:
      - ${GEOSERVER_PORT}:8080
    restart: unless-stopped
    environment:
      - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
      - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - TOMCAT_EXTRAS=${TOMCAT_EXTRAS}
      - INITIAL_MEMORY=${INITIAL_MEMORY}
      - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
     - proxy-net

networks:
  proxy-net:
    external: true
